# Generated by Django 5.0.3 on 2026-03-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Producto')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
